# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install

repos:
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
    language_version: python3.6
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
