name: Sanity-tests@TF

on:
  issue_comment:
    types:
      - created
jobs:
  sanity:
    # This job only runs for '[test]' pull request comments by owner, member
    name: Sanity tests
    runs-on: ubuntu-20.04
    if: |
      github.event.issue.pull_request
      && (contains(github.event.comment.body, '[test]') || contains(github.event.comment.body, '[test-all]'))
      && contains(fromJson('["OWNER","MEMBER"]'), github.event.comment.author_association)
    steps:
      - name: Get pull request number
        id: pr_nr
        run: |
          PR_URL="${{ github.event.comment.issue_url }}"
          echo "::set-output name=PR_NR::${PR_URL##*/}"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ steps.pr_nr.outputs.PR_NR }}/head"

      - name: Get sha
        id: sha
        run: |
          echo "::set-output name=SHA::$(git rev-parse HEAD)"

      - name: Install needed dependences for sanity checks
        id: sched_test
        run: |
          sudo apt-get update && sudo apt-get -y install curl jq make git python3 python3-pip
          pip3 install pre-commit

      - name: Create status check to pending
        id: pending
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat << EOF > pending.json
          {
            "sha": "${{ steps.sha.outputs.SHA }}",
            "state": "pending",
            "context": "Sanity tests"
          }
          EOF
          echo "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ steps.sha.outputs.SHA}} "
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ steps.sha.outputs.SHA }} \
            --data @pending.json

      - name: Run Sanity pre-commit tests
        continue-on-error: true
        id: pre_commit_tests
        run: |
          set +e
          make pre-commit-check
          echo ::set-output name=exit_status::$?

      - name: Switch to final state
        run: |
          echo "Result from pre_commit_tests is ${{ steps.pre_commit_tests.outputs.exit_status }}"

          if [[ ${{ steps.pre_commit_tests.outputs.exit_status }} == 0 ]]; then
            FINAL_STATE="success"
          else
            FINAL_STATE="failure"
          fi
          cat << EOF > final.json
          {
            "sha": "${{ steps.sha.outputs.SHA }}",
            "state": "${FINAL_STATE}",
            "context": "Sanity tests",
            "description": "Build finished"
          }
          EOF
          cat final.json
          curl -X POST -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/${{ steps.sha.outputs.SHA }} \
            --data @final.json
